title: Protein kinase
description: To build a DNN model for protein kinase target compound virtual screening
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
